#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Wed Feb 19 21:58:05 2020

@author: emilym22
"""

from keras.models import load_model
from keras.layers import Input, Dense
from tensorflow import Tensor
from keras import backend as K
from keras.engine import InputLayer
#

import coremltools
output_labels = ['Squat', 'Deadlift']
mlmodel = coremltools.converters.keras.convert('my_model.h5', input_names=['accel'], output_names=['output'], class_labels=output_labels)

mlmodel.author = 'Sophie Saunders and Emily Moise'
mlmodel.short_description = 'Squat/Deadlift recognition'
mlmodel.input_description['accel'] = 'Takes x, y, z acceleration data as input'
mlmodel.output_description['output'] = 'Prediction of Exercise'

mlmodel.save('coreml_model.mlmodel')