# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SmartBellApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod "MetaWear", :subspecs => ['UI', 'AsyncUtils', 'Mocks', 'DFU']
  # Pods for SmartBellApp

  target 'SmartBellAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SmartBellAppUITests' do
    # Pods for testing
  end

end
